Models/TipoAtendimento.cs
namespace Clinica.Models
{
    public class TipoAtendimento
    {
        public int Id { get; set; }
        public int IdClinica { get; set; } 
        public int IdEspecialidade { get; set; }
        public int IdMedico { get; set; }
        public string Descricao { get; set; }  
        public decimal Valor { get; set; }
        public string? NomeEspecialidade { get; set; }
        public string? NomeMedico { get; set; }
        public string? Especializacao { get; set; }
        public string? Nome { get; set; }
    }
}

Controllers/TipoAtendimentoController.cs
using Microsoft.Data.SqlClient;
using Clinica.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList.Extensions;

namespace Clinica.Controllers
{
    public class TipoAtendimentoController : Controller
    {
        private readonly ILogger<TipoAtendimentoController> _logger;
        private readonly DadosContext _context;
        const int itensPorPagina = 5;

        public TipoAtendimentoController(ILogger<TipoAtendimentoController> logger, DadosContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index(int? pagina, string textopesquisa)
        {
            // Verifica se há um valor salvo na sessão para "IdClinica". 
            // Se não houver (ou seja, for nulo), define o valor padrão como 1.
            if (HttpContext.Session.GetInt32("IdClinica") == null)
            {
                HttpContext.Session.SetInt32("IdClinica", 1);
            }

            // Obtém o valor de "IdClinica" da sessão. 
            // Se o valor for nulo, utiliza o valor padrão 0 (através do operador de coalescência nula '??').
            int idClinica = HttpContext.Session.GetInt32("IdClinica") ?? 0;
            int numeroPagina = (pagina ?? 1);

            SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@idClinica", idClinica)
            };
            List<Models.TipoAtendimento> atendimentos = _context.RetornarLista<Models.TipoAtendimento>("sp_consultarTipoAtendimento", parametros);

            // Se o textopesquisa não for nulo ou vazio, filtra os resultados
            if (!string.IsNullOrEmpty(textopesquisa))
            {
                atendimentos = atendimentos
                    .Where(c => c.NomeEspecialidade != null && c.NomeEspecialidade.Contains(textopesquisa, StringComparison.OrdinalIgnoreCase))
                    .ToList();
            }

            ViewBagClinicas();
            return View(atendimentos.ToPagedList(numeroPagina, itensPorPagina));
        }

        public IActionResult Detalhe(int id)
        {
            Models.TipoAtendimento atendimento = new Models.TipoAtendimento();
            int idClinica = HttpContext.Session.GetInt32("IdClinica") ?? 0;

            if (id > 0)
            {
                SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@identificacao", id)
            };
                atendimento = _context.ListarObjeto<Models.TipoAtendimento>("sp_buscarTipoAtendimentoPorId", parametros);
            }
            else
            {
                atendimento.IdClinica = idClinica;
            }

            ViewBagClinicas();
            ViewBagEspecialidades();
            ViewBagMedicos();
            return View(atendimento);
        }

        [HttpPost]
        public IActionResult Detalhe(Models.TipoAtendimento atendimento)
        {
            if (string.IsNullOrEmpty(atendimento.Descricao))
            {
                ModelState.AddModelError("", "O nome não pode ser vazio");
            }

            if (ModelState.IsValid)
            {
                List<SqlParameter> parametros = new List<SqlParameter>(){
                    new SqlParameter("@IdClinica", atendimento.IdClinica),
                    new SqlParameter("@IdEspecialidade", atendimento.IdEspecialidade),
                    new SqlParameter("@IdMedico", atendimento.IdMedico),
                    new SqlParameter("@Descricao", atendimento.Descricao),
                    new SqlParameter("@Valor", atendimento.Valor)
                };
                if (atendimento.Id > 0)
                {
                    parametros.Add(new SqlParameter("@Identificacao", atendimento.Id));
                }
                var retorno = _context.ListarObjeto<RetornoProcedure>(atendimento.Id > 0 ? "sp_atualizarTipoAtendimento" : "sp_inserirTipoAtendimento", parametros.ToArray());

                if (retorno.Mensagem == "Ok")
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", retorno.Mensagem);
                }
            }

            ViewBagClinicas();
            ViewBagEspecialidades();
            ViewBagMedicos();

            return View(atendimento);
        }

        public JsonResult Excluir(int id)
        {
            SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@Identificacao", id)
            };
            var retorno = _context.ListarObjeto<RetornoProcedure>("sp_excluirTipoAtendimento", parametros);
            return new JsonResult(new { Sucesso = retorno.Mensagem == "Excluído", Mensagem = retorno.Mensagem });
        }

        public PartialViewResult ListaPartialView(int idClinica, string textopesquisa)
        {

            SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@IdClinica", idClinica)
            };
            List<Models.TipoAtendimento> atendimentos = _context.RetornarLista<Models.TipoAtendimento>("sp_consultarTipoAtendimento", parametros);

            if (!string.IsNullOrEmpty(textopesquisa))
            {
                atendimentos = atendimentos
                    .Where(c => c.NomeEspecialidade != null && c.NomeEspecialidade.Contains(textopesquisa, StringComparison.OrdinalIgnoreCase))
                    .ToList();
            }

            HttpContext.Session.SetInt32("IdClinica", idClinica);

            return PartialView(atendimentos.ToPagedList(1, itensPorPagina));
        }

        private void ViewBagClinicas()
        {
            SqlParameter[] param = new SqlParameter[]{
                new SqlParameter("@nome", "")
            };
            List<Models.Clinica> clinicas = new List<Models.Clinica>();
            clinicas = _context.RetornarLista<Models.Clinica>("sp_consultarClinica", param);

            ViewBag.Clinicas = clinicas.Select(c => new SelectListItem()
            {
                Text = c.Nome,
                Value = c.Id.ToString()
            }).ToList();
        }

        private void ViewBagMedicos()
        {
            SqlParameter[] param = new SqlParameter[]{
                new SqlParameter("@especializacao", "")
            };
            List<Models.Medico> medicos = new List<Models.Medico>();

            medicos = _context.RetornarLista<Models.Medico>("sp_consultarMedico", param);

            ViewBag.Medicos = medicos.Select(c => new SelectListItem()
            {
                Text = c.Nome,
                Value = c.Id.ToString()
            }).ToList();
        }

        private void ViewBagEspecialidades()
        {
            SqlParameter[] param = new SqlParameter[]{
                new SqlParameter("@nome", "")
            };
            List<Models.Especialidade> especialidades = new List<Models.Especialidade>();

            especialidades = _context.RetornarLista<Models.Especialidade>("sp_consultarEspecialidade", param);

            ViewBag.Especialidades = especialidades.Select(c => new SelectListItem()
            {
                Text = c.Nome,
                Value = c.Id.ToString()
            }).ToList();
        }

    }
}

Views/TipoAtendimento/Detalhe.cshtml
@model TipoAtendimento

@{
    ViewData["Title"] = "Adicionar um novo Atendimento";
}

@section Scripts {

}

<div class="text-center">
    <h4>
        @if (Model.Id > 0)
        {
            @Html.Raw("Editar Atendimento")
            ;
        }
        else
        {
            @Html.Raw("Incluir Atendimento")
            ;
        }
    </h4>
</div>


<form method="POST" asp-action="Detalhe" asp-controller="TipoAtendimento" class="form p-5"
    style="border: 3px solid grey; background: #E6E6E6; border-radius: 15px; margin-top: 30px;">
    <div class="text-danger">@Html.ValidationSummary()</div>

    <div class="row">
        <div class="col-md-6">
            <input asp-for="Id" type="hidden">
            <input asp-for="IdClinica" type="hidden">
            <label class="form-label">Clínica</label>
            <select asp-items="@ViewBag.Clinicas" asp-for="IdClinica" class="form-control" disabled>
                <option>Selecione uma Clínica</option>
            </select>
        </div>
        <div class="col-md-6">
            <label class="form-label">Especialidade</label>
            <select asp-items="@ViewBag.Especialidades" asp-for="IdEspecialidade" class="form-control"
                id="especialidadeSelect">
                <option>Selecione uma Especialidade</option>
            </select>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <label class="form-label">Médico</label>
            <select asp-items="@ViewBag.Medicos" asp-for="IdMedico" class="form-control">
                <option value="">Selecione um(a) Médico(a)</option>
            </select>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <label for="inputDescricao" class="form-label">Descrição</label>
            <input asp-for="Descricao" type="text" class="form-control">
        </div>
        <div class="col-md-6">
            <label class="form-label">Valor</label>
            <input asp-for="Valor" type="text" class="form-control">
        </div>
    </div>

    <input type="submit" value="Salvar" class="btn btn-success" style="margin-top: 30px; margin-bottom: 15px;">
    <input type="button" value="Voltar" class="btn btn-success" onclick="Voltar()"
        style="margin-top: 30px; margin-bottom: 15px"></td>
</form>

<script>

    function Voltar() {
        window.location.href = "http://localhost:5210/TipoAtendimento";
    }

    document.getElementById('especialidadeSelect').addEventListener('change', function () {
        var especialidadeId = this.value;

        // Verifica se foi selecionada uma especialidade
        if (especialidadeId) {
            // Faz a requisição AJAX para atualizar os médicos
            $.ajax({
                url: '@Url.Action("CarregarMedicos", "TipoAtendimento")',
                data: { idEspecialidade: especialidadeId },
                success: function (data) {
                    // Atualiza o select de médicos com os dados retornados
                    var medicoSelect = $('#IdMedico');
                    medicoSelect.empty();
                    medicoSelect.append('<option value="">Selecione um(a) Médico(a)</option>');
                    data.forEach(function (medico) {
                        medicoSelect.append('<option value="' + medico.value + '">' + medico.text + '</option>');
                    });
                },
                error: function () {
                    alert("Erro ao carregar médicos.");
                }
            });
        }
    });

    // Adiciona validação ao clicar no botão de salvar
    document.querySelector('form').addEventListener('submit', function (event) {
        var descricao = document.querySelector('[name="Descricao"]').value;
        var medico = document.querySelector('[name="IdMedico"]').value;
        var especialidade = document.querySelector('[name="IdEspecialidade"]').value;

        if (!descricao || !medico || !especialidade) {
            event.preventDefault(); // Impede a submissão do formulário
            alert("Por favor, preencha todos os campos obrigatórios.");
        }
    });

</script>

Views/TipoAtendimento/Index.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@model X.PagedList.IPagedList<TipoAtendimento>

@{
    ViewData["Title"] = "Tipos de Atendimentos";
}

@section Scripts {

}

<div class="text-center">
    <h4>Atendimentos</h4>
    <select id="idClinica" asp-items="@ViewBag.Clinicas" class="form-control" onchange="Pesquisar()"></select>
    <input type="text" id="textopesquisa" class="form-control" onkeyup="VerificarDigitacao(event)"
        value="@HttpContextAccessor.HttpContext.Session.GetString("TextoPesquisa")" placeholder="Pesquisar">
    <input type="button" value="Limpar" onclick="Limpar()" class="btn btn-primary">
    <input type="button" value="Pesquisar" onclick="Pesquisar()" class="btn btn-primary">
    <a asp-area="" asp-controller="TipoAtendimento" asp-action="Detalhe">
        <input type="button" value="Novo" class="btn btn-primary" style="margin-top: 30px; margin-bottom: 30px;">
    </a>
    <div id="divpartial">
        <partial name="~/Views/TipoAtendimento/ListaPartialView.cshtml" />
    </div>
</div>

<script>

    function Limpar() {
        $('#textopesquisa').val('');
        Pesquisar();
        recarregarPagina();
    }

    //limpar textopesquisa ao recarregar a página
    document.addEventListener("DOMContentLoaded", function () {
        document.getElementById("textopesquisa").value = "";
    });

    function Pesquisar() {
        var result = $('#textopesquisa').val();
        var idClinica = $('#idClinica').val();
        var url = "/TipoAtendimento/ListaPartialView";
        var parametros = { pagina: 1, textopesquisa: result, idClinica: idClinica };
        $.get(url, parametros)
            .done(function (data) {
                $('#divpartial').html(data);
            });
    }

    function recarregarPagina() {
        location.reload();
    }

    document.getElementById("limpar").addEventListener("click", recarregarPagina);

    function VerificarDigitacao(e) {
        var code = (e.keyCode ? e.keyCode : e.which);
        if (code == 13) {
            Pesquisar();
        }
    }

    function Excluir(id) {
        var result = confirm("Tem certeza que quer excluir?");
        if (result) {
            var url = "/TipoAtendimento/Excluir";
            var parametros = { id: id };
            $.get(url, parametros)
                .done(function (data) {

                    if (data.sucesso) {
                        document.location.reload(true);
                    } else {
                        alert(data.mensagem);
                    }

                });
        }
    }

</script>

Views/TipoAtendimento/ListaPartialView.cshtml
@model X.PagedList.IPagedList<TipoAtendimento>
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Código</th>
            <th>Especialidade</th>
            <th>Medico</th>
            <th>Descrição</th>
            <th>Valor</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <td>@Model[i].Id</td>
                <td>@Model[i].NomeEspecialidade</td>
                <td>@Model[i].NomeMedico</td>
                <td>@Model[i].Descricao</td>
                <td>@Model[i].Valor</td>
                <td>
                    <input type="button" value="Editar" class="btn btn-dark"
                        onclick="javascript:window.location=`/TipoAtendimento/Detalhe/${@Model[i].Id}`">
                    <input type="button" value="Excluir" class="btn btn-danger" onclick="Excluir(@Model[i].Id)">
                </td>
            </tr>
        }
    </tbody>
</table>
@Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina }))