Models/Especialidade.cs
namespace Clinica.Models
{
    public class Especialidade
    {
        public int Id { get; set; }
        public string? Nome { get; set; }
        public string Tipo { get; set; }
    }
}

Controllers/EspecialidadeController.cs
using Microsoft.Data.SqlClient;
using Clinica.Models;
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Clinica.Controllers
{
    public class EspecialidadeController : Controller
    {
        private readonly ILogger<EspecialidadeController> _logger;
        private readonly DadosContext _context;
        const int itensPorPagina = 5;
        public EspecialidadeController(ILogger<EspecialidadeController> logger, DadosContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index(int? pagina)
        {
            var nome = "";
            int numeroPagina = (pagina ?? 1);

            SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@nome", nome)
            };

            List<Models.Especialidade> especialidades = _context.RetornarLista<Models.Especialidade>("sp_consultarEspecialidade", parametros);

            return View(especialidades.ToPagedList(numeroPagina, itensPorPagina));
        }

        public IActionResult Detalhe(int id)
        {
            Models.Especialidade especialidade = new Models.Especialidade();

            if (id > 0)
            {
                SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@identificacao", id)
            };
                especialidade = _context.ListarObjeto<Models.Especialidade>("sp_buscarEspecialidadePorId", parametros);
            }


            return View(especialidade);
        }

        [HttpPost]
        public IActionResult Detalhe(Models.Especialidade especialidade)
        {
            
            if (string.IsNullOrEmpty(especialidade.Nome))
            {
                ModelState.AddModelError("", "O Nome deve ser informado");
            }
            if (string.IsNullOrEmpty(especialidade.Tipo))
            {
                ModelState.AddModelError("", "O Tipo deve ser informado");
            }

            if (ModelState.IsValid)
            {
                List<SqlParameter> parametros = new List<SqlParameter>(){
                    new SqlParameter("@Nome", especialidade.Nome),
                    new SqlParameter("@Tipo", especialidade.Tipo)
                };

                if (especialidade.Id > 0)
                {
                    parametros.Add(new SqlParameter("@Identificacao", especialidade.Id));
                }

                var retorno = _context.ListarObjeto<RetornoProcedure>(especialidade.Id > 0 ? "sp_atualizarEspecialidade" : "sp_inserirEspecialidade", parametros.ToArray());

                if (retorno.Mensagem == "Ok")
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", retorno.Mensagem);
                }
            }

            return View(especialidade);
        }

        public JsonResult Excluir(int id)
        {
            SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@Identificacao", id)
            };

            var retorno = _context.ListarObjeto<RetornoProcedure>("sp_excluirEspecialidade", parametros);

            return new JsonResult(new { Sucesso = retorno.Mensagem == "Excluído", Mensagem = retorno.Mensagem });
        }

        public PartialViewResult ListaPartialView(string nome)
        {
            SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@nome", nome)
            };

            List<Models.Especialidade> especialidades = _context.RetornarLista<Models.Especialidade>("sp_consultarEspecialidade", parametros);

            if (string.IsNullOrEmpty(nome))
            {
                HttpContext.Session.Remove("TextoPesquisa");
            }
            else
            {
                HttpContext.Session.SetString("TextoPesquisa", nome);
            }

            return PartialView(especialidades.ToPagedList(1, itensPorPagina));
        }

    }
}

Views/Especialidade/Detalhe.cshtml
@model Especialidade

@{
    ViewData["Title"] = "Adicionar uma nova Especialidade";
}

<div class="text-center">
    <h4>
        @if (Model.Id > 0)
        {
        @Html.Raw("Editar Especialidade")
            ;
        }
        else
        {
        @Html.Raw("Incluir Especialidade")
            ;
        }
    </h4>
</div>

<form method="POST" asp-action="Detalhe" asp-controller="Especialidade" class="form p-5"
      style="border: 3px solid grey; background: #E6E6E6; border-radius: 15px; margin-top: 30px;">
    <div class="text-danger">@Html.ValidationSummary()</div>
    <div class="row">
        <div class="col-md-6">
            <input asp-for="Id" type="hidden" class="form-control">
            <label for="inputNome" class="form-label">Nome</label>
            <select asp-for="Nome" class="form-control">
                <option value="">Selecione uma Especialidade</option>
                <option>Cardiologista</option>
                <option>Clínico Geral</option>
                <option>Coleta de Sangue</option>
                <option>Dermatologista</option>
                <option>Fisioterapeuta</option>
                <option>Ginecologista</option>
                <option>Hematologista</option>
                <option>Nutricionista</option>
                <option>Oftalmologista</option>
                <option>Ortopedista</option>
                <option>Pediatra</option>
                <option>Raio-x</option>
                <option>Ultrassonografia</option>                
            </select>
        </div>
        <div class="col-md-6">
            <label for="inputTipo" class="form-label">Tipo</label>
            <select asp-for="Tipo" class="form-control">
                <option>Selecione o Tipo</option>
                <option>Consulta</option>
                <option>Exame</option>
            </select>
        </div>
    </div>
    <input type="submit" value="Salvar" class="btn btn-success" style="margin-top: 30px; margin-bottom: 15px;">
    <input type="button" value="Voltar" class="btn btn-success" onclick="Voltar()"
           style="margin-top: 30px; margin-bottom: 15px;"></td>
</form>

<script>

    function Voltar() {
        window.location.href = "http://localhost:5210/Especialidade";
    }

</script>

Views/Especialidade/Index.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@model X.PagedList.IPagedList<Especialidade>

@{
    ViewData["Title"] = "Especialidades";
}

@section Scripts {

}

<div class="text-center">
    <h4>Especialidades</h4>
    <input type="text" id="textopesquisa" class="form-control" onkeyup="VerificarDigitacao(event)"
        value="@HttpContextAccessor.HttpContext.Session.GetString("TextoPesquisa")" placeholder="Pesquisar">
    <input type="button" id="limpar" value="Limpar" onclick="Limpar()" class="btn btn-primary">
    <input type="button" value="Pesquisar" onclick="Pesquisar()" class="btn btn-primary" style="margin-top: 30px; margin-bottom: 30px;">
    <a asp-area="" asp-controller="Especialidade" asp-action="Detalhe"><input type="button" value="Novo"
            class="btn btn-primary" style="margin-top: 30px; margin-bottom: 30px;">
    </a>
    <div id="divpartial">
        <partial name="~/Views/Especialidade/ListaPartialView.cshtml" />
    </div>
</div>

<script>

    function Limpar() {
        $('#textopesquisa').val('');
        Pesquisar();
    }
    //limpar textopesquisa ao recarregar a página
    document.addEventListener("DOMContentLoaded", function () {
        document.getElementById("textopesquisa").value = "";
    });
    function Pesquisar() {
        var result = $('#textopesquisa').val();
        var url = "/Especialidade/ListaPartialView";
        var parametros = { nome: result };
        $.get(url, parametros)
            .done(function (data) {
                $('#divpartial').html(data);
            });
    }
    function recarregarPagina() {
        location.reload();
    }
    document.getElementById("limpar").addEventListener("click", recarregarPagina);
    function VerificarDigitacao(e) {
        var code = (e.keyCode ? e.keyCode : e.which);
        if (code == 13) {
            Pesquisar();
        }
    }
    function Excluir(id) {
        var result = confirm("Tem certeza que quer excluir?");
        if (result) {
            var url = "/Especialidade/Excluir";
            var parametros = { id: id };
            $.get(url, parametros)
                .done(function (data) {
                    if (data.sucesso) {
                        document.location.reload(true);
                    } else {
                        alert(data.mensagem);
                    }
                });
        }
    }

</script>

Views/Especialidade/ListaPartialView.cshtml
@model X.PagedList.IPagedList<Especialidade>
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Nome</th>
            <th>Tipo</th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <td>@Model[i].Nome</td>
                <td>@Model[i].Tipo</td>
                <td>
                    <input type="button" value="Editar" class="btn btn-dark"
                        onclick="javascript:window.location=`/Especialidade/Detalhe/${@Model[i].Id}`">
                    <input type="button" value="Excluir" class="btn btn-danger" onclick="Excluir(@Model[i].Id)">
                </td>
            </tr>
        }
    </tbody>
</table>
@Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina }))