Models/Clinica.cs
namespace Clinica.Models
{
    public class Clinica
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public string Endereco { get; set; }
        public decimal Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string CEP { get; set; }
    }
}

Controllers/ClinicaController.cs
using Microsoft.Data.SqlClient;
using Clinica.Models;
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;

namespace Clinica.Controllers
{
    public class ClinicaController : Controller
    {
        private readonly ILogger<ClinicaController> _logger;
        private readonly DadosContext _context ;
        const int itensPorPagina = 5;
  
        public ClinicaController(ILogger<ClinicaController> logger, DadosContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index(int? pagina)
        {
            var nome = "";
            int numeroPagina = (pagina ?? 1);

            SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@nome", nome)
            };
            List<Models.Clinica> clinicas = _context.RetornarLista<Models.Clinica>("sp_consultarClinica", parametros);
            
            return View(clinicas.ToPagedList(numeroPagina, itensPorPagina));
        }

        public IActionResult Detalhe(int id)
        {
            Models.Clinica clinica = new Models.Clinica();
            if (id > 0)  {
                SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@identificacao", id)
            };
                clinica = _context.ListarObjeto<Models.Clinica>("sp_buscarClinicaPorId", parametros); 
            }
                   
            return View(clinica);
        }

        [HttpPost]
        public IActionResult Detalhe(Models.Clinica clinica){
            if(string.IsNullOrEmpty(clinica.Nome)){
                ModelState.AddModelError("", "O nome não pode ser vazio");
            } 
            if(string.IsNullOrEmpty(clinica.Telefone)){
                ModelState.AddModelError("", "O Telefone deve ser informado");
            }
            if(string.IsNullOrEmpty(clinica.Endereco)){
                ModelState.AddModelError("", "O Endereço deve ser informado");
            }
            if(string.IsNullOrEmpty(clinica.Bairro)){
                ModelState.AddModelError("", "O Bairro deve ser informado");
            }
            if(string.IsNullOrEmpty(clinica.Cidade)){
                ModelState.AddModelError("", "O Cidade deve ser informado");
            }
            if(string.IsNullOrEmpty(clinica.Estado)){
                ModelState.AddModelError("", "O Estado deve ser informado");
            }
            if(string.IsNullOrEmpty(clinica.Pais)){
                ModelState.AddModelError("", "O País deve ser informado");
            }
            if(string.IsNullOrEmpty(clinica.CEP)){
                ModelState.AddModelError("", "O CEP deve ser informado");
            }


            if(ModelState.IsValid){
           
                List<SqlParameter> parametros = new List<SqlParameter>(){
                    new SqlParameter("@Nome", clinica.Nome),
                    new SqlParameter("@Telefone", clinica.Telefone),
                    new SqlParameter("@Endereco", clinica.Endereco),
                    new SqlParameter("@Numero", clinica.Numero),
                    new SqlParameter("@Complemento", clinica.Complemento),
                    new SqlParameter("@Bairro", clinica.Bairro),
                    new SqlParameter("@Cidade", clinica.Cidade),
                    new SqlParameter("@Estado", clinica.Estado),
                    new SqlParameter("@Pais", clinica.Pais),
                    new SqlParameter("@CEP", clinica.CEP)
                };
                if (clinica.Id > 0){
                    parametros.Add(new SqlParameter("@Identificacao", clinica.Id));
                }
                var retorno = _context.ListarObjeto<RetornoProcedure>(clinica.Id > 0? "sp_atualizarClinica" : "sp_inserirClinica", parametros.ToArray());
            
                if (retorno.Mensagem == "Ok"){
                    return RedirectToAction("Index");
                } else {
                    ModelState.AddModelError("", retorno.Mensagem);
                }
            }
            return View(clinica);
        }

        public JsonResult Excluir(int id){
            SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@Identificacao", id)
            };
            var retorno = _context.ListarObjeto<RetornoProcedure>("sp_excluirClinica", parametros);
            return new JsonResult(new {Sucesso = retorno.Mensagem == "Excluído", Mensagem = retorno.Mensagem });
        }

        public PartialViewResult ListaPartialView(string nome){
            SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@nome", nome)
            };
            List<Models.Clinica> clinicas = _context.RetornarLista<Models.Clinica>("sp_consultarClinica", parametros);
            if (string.IsNullOrEmpty(nome)){
                HttpContext.Session.Remove("TextoPesquisa");
            } else {
            HttpContext.Session.SetString("TextoPesquisa", nome);
            }

            return PartialView(clinicas.ToPagedList(1, itensPorPagina));
        }
    }
}

Views/Clinica/Detalhe.cshtml
@model Clinica

@{
    ViewData["Title"] = "Adicionar uma nova Clínica";
}


<div class="text-center">
    <h4>@if (Model.Id > 0)
        {
            @Html.Raw("Editar Clínica")
            ;
        }
        else
        {
            @Html.Raw("Incluir Clínica")
            ;
        }
    </h4>
</div>

<form method="POST" asp-action="Detalhe" asp-controller="Clinica" class="form p-5"
    style="border: 3px solid grey; background: #E6E6E6; border-radius: 15px; margin-top: 30px;">
    <div class="text-danger">@Html.ValidationSummary()</div>

    <div class="row">
        <div class="col-md-6">
            <input asp-for="Id" type="hidden" class="form-control">
            <label for="inputNome" class="form-label">Nome</label>
            <input asp-for="Nome" type="text" class="form-control">
        </div>

        <div class="col-md-6">
            <label for="inputEndereco" class="form-label">Endereço</label>
            <input asp-for="Endereco" type="text" class="form-control" placeholder="Rua/Avenida">
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <label for="inputNumero" class="form-label">Número</label>
            <input asp-for="Numero" type="number" class="form-control" placeholder="Nº">
        </div>
        <div class="col-md-6">
            <label for="inputComplemento" class="form-label">Complemento</label>
            <input asp-for="Complemento" type="text" class="form-control"
                placeholder="Apartamento,condomínio,sala,etc.(opcional)">
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <label for="inputBairro" class="form-label">Bairro</label>
            <input asp-for="Bairro" type="text" class="form-control">
        </div>
        <div class="col-md-6">
            <label for="inputCidade" class="form-label">Cidade</label>
            <input asp-for="Cidade" type="text" class="form-control">
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <label for="inputEstado" class="form-label">Estado</label>
            <input asp-for="Estado" type="text" class="form-control" placeholder="UF">
        </div>
        <div class="col-md-6">
            <label for="inputPais" class="form-label">País</label>
            <input asp-for="Pais" type="text" class="form-control">
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <label for="inputCEP" class="form-label">CEP</label>
            <input asp-for="CEP" type="text" class="form-control" maxlength="9">
        </div>
        <div class="col-md-6">
            <label for="inputTelefone" class="form-label">Telefone</label>
            <input asp-for="Telefone" type="text" class="form-control" maxlength="15">
        </div>
    </div>

    <input type="submit" value="Salvar" class="btn btn-success" style="margin-top: 30px; margin-bottom: 15px;">
    <input type="button" value="Voltar" class="btn btn-success" onclick="Voltar()"
        style="margin-top: 30px; margin-bottom: 15px;"></td>
</form>

<script>

    function Voltar() {
        window.location.href = "http://localhost:5210/Clinica";
    }

    window.onload = function () {
        $("#CEP").inputmask('99999-999');
        $("#Telefone").inputmask('(99)99999-9999');
    }

</script>

Views/Clinica/Index.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@model X.PagedList.IPagedList<Clinica>

@{
    ViewData["Title"] = "Clínicas";
}

@section Scripts {

}

<div class="text-center">
    <h4>Clínicas</h4>
    <input type="text" id="textopesquisa" class="form-control" onkeyup="VerificarDigitacao(event)"
        value="@HttpContextAccessor.HttpContext.Session.GetString("TextoPesquisa")" placeholder="Pesquisar">
    <input type="button" id="limpar" value="Limpar" onclick="Limpar()" class="btn btn-primary">
    <input type="button" value="Pesquisar" onclick="Pesquisar()" class="btn btn-primary">

    <a asp-area="" asp-controller="Clinica" asp-action="Detalhe"><input type="button" value="Novo"
            class="btn btn-primary" style="margin-top: 30px; margin-bottom: 30px;"></a>
    <div id="divpartial">
        <partial name="~/Views/Clinica/ListaPartialView.cshtml" />
    </div>
</div>

<script>

    function Limpar() {
        $('#textopesquisa').val('');
        Pesquisar();
    }

    //limpar textopesquisa ao recarregar a página
    document.addEventListener("DOMContentLoaded", function () {
        document.getElementById("textopesquisa").value = "";
    });

    function Pesquisar() {
        var result = $('#textopesquisa').val();
        var url = "/Clinica/ListaPartialView";
        var parametros = { nome: result };
        $.get(url, parametros)
            .done(function (data) {
                $('#divpartial').html(data);
            });
    }

    function recarregarPagina() {
        location.reload();
    }

    document.getElementById("limpar").addEventListener("click", recarregarPagina);

    function VerificarDigitacao(e) {
        var code = (e.keyCode ? e.keyCode : e.which);
        if (code == 13) {
            Pesquisar();
        }
    }

    function Excluir(id) {
        var result = confirm("Tem certeza que quer excluir?");
        if (result) {
            var url = "/Clinica/Excluir";
            var parametros = { id: id };
            $.get(url, parametros)
                .done(function (data) {

                    if (data.sucesso) {
                        document.location.reload(true);
                    } else {
                        alert(data.mensagem);
                    }

                });
        }
    }
    
</script>

Views/Clinica/ListaPartialView.cshtml
@model X.PagedList.IPagedList<Clinica>
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Nome</th>
            <th>Cidade</th>

            <th>Telefone</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <td>@Model[i].Nome</td>
                <td>@Model[i].Cidade</td>
                <td>@Model[i].Telefone</td>
                <td><input type="button" value="Editar" class="btn btn-dark"
                        onclick="javascript:window.location=`/Clinica/Detalhe/${@Model[i].Id}`">
                    <input type="button" value="Excluir" class="btn btn-danger" onclick="Excluir(@Model[i].Id)">
                </td>

            </tr>
        }

    </tbody>
</table>

@Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina }))