Models/Agendamento.cs
namespace Clinica.Models
{
    public class Agendamento
    {
        public int Id { get; set; }
        public int IdTipoAtendimento { get; set; }
        public int IdPaciente { get; set; }
        public DateTime DataHora { get; set; } = DateTime.Now;
        public DateTime? DataHoraConfirmacao { get; set; } 
        public bool EstevePresente { get; set; }
        public int IdClinica { get; set; }
        public string? NomePaciente { get; set; }
        public string? NomeEspecialidade { get; set; }
        public string? NomeMedico { get; set; }
    }
} 

Controllers/AgendamentoController.cs
using Microsoft.Data.SqlClient;
using Clinica.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList.Extensions;

namespace Clinica.Controllers
{
    public class AgendamentoController : Controller
    {
        private readonly ILogger<AgendamentoController> _logger;
        private readonly DadosContext _context;
        const int itensPorPagina = 5;

        public AgendamentoController(ILogger<AgendamentoController> logger, DadosContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index(int? pagina, string textopesquisa)
        {
            // Verifica se há um valor salvo na sessão para "IdClinica". 
            // Se não houver (ou seja, for nulo), define o valor padrão como 1.
            if (HttpContext.Session.GetInt32("IdClinica") == null)
            {
                HttpContext.Session.SetInt32("IdClinica", 1);
            }

            // Obtém o valor de "IdClinica" da sessão. 
            // Se o valor for nulo, utiliza o valor padrão 0 (através do operador de coalescência nula '??').
            int idClinica = HttpContext.Session.GetInt32("IdClinica") ?? 0;
            int numeroPagina = (pagina ?? 1);

            SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@idClinica", idClinica)
            };
            List<Models.Agendamento> agendamentos = _context.RetornarLista<Models.Agendamento>("sp_consultarAgendamento", parametros);

            // Se o textopesquisa não for nulo ou vazio, filtra os resultados
            if (!string.IsNullOrEmpty(textopesquisa))
            {
                agendamentos = agendamentos
                    .Where(c => c.NomeEspecialidade != null && c.NomeEspecialidade.Contains(textopesquisa, StringComparison.OrdinalIgnoreCase))
                    .ToList();
            }

            ViewBagClinicas();
            return View(agendamentos.ToPagedList(numeroPagina, itensPorPagina));
        }

        public IActionResult Detalhe(int id)
        {
            Models.Agendamento agendamento = new Models.Agendamento();
            int idClinica = HttpContext.Session.GetInt32("IdClinica") ?? 0;

            if (id > 0)
            {
                SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@identificacao", id)
            };
                agendamento = _context.ListarObjeto<Models.Agendamento>("sp_buscarAgendamentoPorId", parametros);
            }
            else
            {
                agendamento.IdClinica = idClinica;
                agendamento.DataHora = DateTime.Now; // Data padrão para novos agendamentos
            }

            // Popula ViewBag com horários disponíveis na data do agendamento
            ViewBag.HorariosDisponiveis = ObterHorariosDisponiveis(agendamento.DataHora.Date)
                .Select(horario => new SelectListItem
                {
                    Value = horario,
                    Text = horario,
                    Selected = agendamento.DataHora.ToString("HH:mm") == horario // Deixa o horário salvo selecionado
                })
                .ToList();

            ViewBagClinicas();
            ViewBagAtendimentos(agendamento.IdClinica);
            ViewBagPacientes();
            return View(agendamento);
        }

        [HttpPost]
        public IActionResult Detalhe(Models.Agendamento agendamento, string data, string horario)
        {
            if (ModelState.IsValid)
            {
                // Combinar data e horário
                agendamento.DataHora = DateTime.Parse($"{data} {horario}");

                List<SqlParameter> parametros = new List<SqlParameter>(){
                    new SqlParameter("@IdTipoAtendimento", agendamento.IdTipoAtendimento),
                    new SqlParameter("@IdPaciente", agendamento.IdPaciente),
                    new SqlParameter("@DataHora", agendamento.DataHora),
                    new SqlParameter("@DataHoraConfirmacao", (object)agendamento.DataHoraConfirmacao ?? DBNull.Value),
                    new SqlParameter("@EstevePresente", agendamento.EstevePresente)
                };
                if (agendamento.Id > 0)
                {
                    parametros.Add(new SqlParameter("@Identificacao", agendamento.Id));
                }
                var retorno = _context.ListarObjeto<RetornoProcedure>(agendamento.Id > 0 ? "sp_atualizarAgendamento" : "sp_inserirAgendamento", parametros.ToArray());

                if (retorno.Mensagem == "Ok")
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", retorno.Mensagem);
                }
            }

            ViewBag.HorariosDisponiveis = ObterHorariosDisponiveis(agendamento.DataHora.Date);
            ViewBagClinicas();
            ViewBagAtendimentos(agendamento.IdClinica);
            ViewBagPacientes();
            return View(agendamento);
        }

        public JsonResult Excluir(int id)
        {
            SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@Identificacao", id)
            };
            var retorno = _context.ListarObjeto<RetornoProcedure>("sp_excluirAgendamento", parametros);
            return new JsonResult(new { Sucesso = retorno.Mensagem == "Excluído", Mensagem = retorno.Mensagem });
        }

        public PartialViewResult ListaPartialView(int idClinica, string textopesquisa)
        {

            SqlParameter[] parametros = new SqlParameter[]{
                new SqlParameter("@IdClinica", idClinica)
            };
            List<Models.Agendamento> agendamentos = _context.RetornarLista<Models.Agendamento>("sp_consultarAgendamento", parametros);

            if (!string.IsNullOrEmpty(textopesquisa))
            {
                agendamentos = agendamentos
                    .Where(c => c.NomeEspecialidade != null && c.NomeEspecialidade.Contains(textopesquisa, StringComparison.OrdinalIgnoreCase))
                    .ToList();
            }

            HttpContext.Session.SetInt32("IdClinica", idClinica);

            return PartialView(agendamentos.ToPagedList(1, itensPorPagina));
        }

        [HttpGet]
        public JsonResult GetHorariosDisponiveis(DateTime data)
        {
            // Lógica para buscar os horários disponíveis
            var horariosDisponiveis = ObterHorariosDisponiveis(data);

            return Json(horariosDisponiveis);
        }

        private List<string> ObterHorariosDisponiveis(DateTime data)
        {
            // Lista de horários fixos
            var horarios = new List<string>
            {
                "08:00", "09:00", "10:00", "11:00", "14:00", "15:00", "16:00"
            };

            // Início e fim do dia
            var inicioDoDia = data.Date;
            var fimDoDia = data.Date.AddDays(1).AddTicks(-1);

            // Filtrar os horários ocupados na tabela Agendamento
            var horariosOcupados = _context.RetornarLista<Agendamento>("sp_consultarAgendamentos", new SqlParameter[]
            {
                new SqlParameter("@InicioDoDia", inicioDoDia),
                new SqlParameter("@FimDoDia", fimDoDia)
            }).Select(a => a.DataHora.ToString("HH:mm")).ToList();

            // Retornar apenas os horários disponíveis
            return horarios.Except(horariosOcupados).ToList();
        }

        public JsonResult CarregarMedicos(int idEspecialidade)
        {
            SqlParameter[] param = new SqlParameter[] {
            new SqlParameter("@IdEspecialidade", idEspecialidade)
            };

            List<Models.Medico> medicos = _context.RetornarLista<Models.Medico>("sp_consultarMedicoPorEspecialidade", param);

            var medicosSelectList = medicos.Select(c => new
            {
                Value = c.Id,
                Text = c.Nome
            }).ToList();

            return Json(medicosSelectList);
        }

        private void ViewBagClinicas()
        {
            SqlParameter[] param = new SqlParameter[]{
                new SqlParameter("@nome", "")
            };
            List<Models.Clinica> clinicas = new List<Models.Clinica>();
            clinicas = _context.RetornarLista<Models.Clinica>("sp_consultarClinica", param);

            ViewBag.Clinicas = clinicas.Select(c => new SelectListItem()
            {
                Text = c.Nome,
                Value = c.Id.ToString()
            }).ToList();
        }

        private void ViewBagAtendimentos(int idClinica)
        {
            SqlParameter[] param = new SqlParameter[]{
                new SqlParameter("@idClinica", idClinica)
            };
            List<Models.TipoAtendimento> atendimentos = new List<Models.TipoAtendimento>();

            atendimentos = _context.RetornarLista<Models.TipoAtendimento>("sp_consultarTipoAtendimento", param);

            ViewBag.Atendimentos = atendimentos.Select(c => new SelectListItem()
            {
                Text = c.NomeEspecialidade + " - " + c.NomeMedico,
                Value = c.Id.ToString()
            }).ToList();
        }

        private void ViewBagPacientes()
        {
            SqlParameter[] param = new SqlParameter[]{
                new SqlParameter("@nome", "")
            };
            List<Models.Paciente> pacientes = new List<Models.Paciente>();

            pacientes = _context.RetornarLista<Models.Paciente>("sp_consultarPaciente", param);

            ViewBag.Pacientes = pacientes.Select(c => new SelectListItem()
            {
                Text = c.Nome,
                Value = c.Id.ToString()
            }).ToList();
        }

    }
}

Views/Agendamento/Detalhe.cshtml
@model Agendamento

@{
    ViewData["Title"] = "Adicionar um novo Agendamento";
}

@section Scripts {

}

<div class="text-center">
    <h4>
        @if (Model.Id > 0)
        {
            @Html.Raw("Editar Agendamento")
            ;
        }
        else
        {
            @Html.Raw("Incluir Agendamento")
            ;
        }
    </h4>
</div>


<form method="POST" asp-action="Detalhe" asp-controller="Agendamento" class="form p-5"
    style="border: 3px solid grey; background: #E6E6E6; border-radius: 15px; margin-top: 30px;">
    <div class="text-danger">@Html.ValidationSummary()</div>

    <div class="row">
        <div class="col-md-6">
            <input asp-for="Id" type="hidden">
            <input asp-for="IdClinica" type="hidden">
            <label class="form-label">Clínica</label>
            <select asp-items="@ViewBag.Clinicas" asp-for="IdClinica" class="form-control" disabled>
                <option>Selecione uma Clínica</option>
            </select>
        </div>
        <div class="col-md-6">
            <label class="form-label">Atendimento</label>
            <select asp-items="@ViewBag.Atendimentos" asp-for="IdTipoAtendimento" class="form-control">
                <option>Selecione um Atendimento</option>
            </select>

        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <label class="form-label">Paciente</label>
            <select asp-items="@ViewBag.Pacientes" asp-for="IdPaciente" class="form-control">
                <option value="">Selecione um(a) Paciente</option>
            </select>
        </div>
        <div class="col-md-6">
            <label for="inputDataHora" class="form-label">Data</label>
            <input asp-for="DataHora" type="date" class="form-control" id="dataAgendamento" name="data"
                value="@Model.DataHora.ToString("yyyy-MM-dd")">
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <label for="horariosDisponiveis" class="form-label">Horários Disponíveis</label>
            <select id="horariosDisponiveis" class="form-control" name="horario">
                @foreach (var item in (List<SelectListItem>)ViewBag.HorariosDisponiveis)
                {
                    if (item.Selected)
                    {
                        <option value="@item.Value" selected>@item.Text</option>
                    }
                    else
                    {
                        <option value="@item.Value">@item.Text</option>
                    }
                }
            </select>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <label for="inputDataHoraConfirmacao" class="form-label">Confirmação do Agendamento</label>
            <input asp-for="DataHoraConfirmacao" type="date" class="form-control">
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-check form-switch d-flex align-items-center mt-3"> <!-- Adicionei mt-3 aqui -->
                <input asp-for="EstevePresente" type="checkbox" class="form-check-input" id="estevePresenteSwitch">
                <label class="form-check-label ms-2" for="estevePresenteSwitch" style="font-weight: normal;">Compareceu
                    no dia</label>
            </div>
        </div>
    </div>

    <input type="submit" value="Salvar" class="btn btn-success" style="margin-top: 30px; margin-bottom: 15px;">
    <input type="button" value="Voltar" class="btn btn-success" onclick="Voltar()"
        style="margin-top: 30px; margin-bottom: 15px"></td>
</form>

<script>

    function Voltar() {
        window.location.href = "http://localhost:5210/Agendamento";
    }

    document.getElementById("horariosDisponiveis").addEventListener("change", function () {
        const horarioSelecionado = this.value; // Obtém o horário selecionado

        if (horarioSelecionado) {
            // Remove o horário selecionado da lista de opções
            const dropdown = document.getElementById("horariosDisponiveis");
            const opcoes = Array.from(dropdown.options);

            // Filtra a lista para excluir o horário selecionado
            dropdown.innerHTML = ""; // Limpa o dropdown
            opcoes.forEach(option => {
                if (option.value !== horarioSelecionado) {
                    dropdown.appendChild(option);
                }
            });

            // Reinsere a opção selecionada para manter o estado visual
            const optionSelecionada = document.createElement("option");
            optionSelecionada.value = horarioSelecionado;
            optionSelecionada.textContent = horarioSelecionado;
            optionSelecionada.selected = true; // Deixa selecionado
            dropdown.appendChild(optionSelecionada);
        }
    });

</script>

Views/Agendamento/Index.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@model X.PagedList.IPagedList<Agendamento>

@{
    ViewData["Title"] = "Agendamentos";
}

@section Scripts {

}

<div class="text-center">
    <h4>Agendamentos</h4>
    <select id="idClinica" asp-items="@ViewBag.Clinicas" class="form-control" onchange="Pesquisar()"></select>
    <input type="text" id="textopesquisa" class="form-control" onkeyup="VerificarDigitacao(event)"
        value="@HttpContextAccessor.HttpContext.Session.GetString("TextoPesquisa")" placeholder="Pesquisar">
    <input type="button" value="Limpar" onclick="Limpar()" class="btn btn-primary">
    <input type="button" value="Pesquisar" onclick="Pesquisar()" class="btn btn-primary">
    <a asp-area="" asp-controller="Agendamento" asp-action="Detalhe">
        <input type="button" value="Novo" class="btn btn-primary" style="margin-top: 30px; margin-bottom: 30px;">
    </a>
    <div id="divpartial">
        <partial name="~/Views/Agendamento/ListaPartialView.cshtml" />
    </div>
</div>

<script>

    function Limpar() {
        $('#textopesquisa').val('');
        Pesquisar();
        recarregarPagina();
    }

    //limpar textopesquisa ao recarregar a página
    document.addEventListener("DOMContentLoaded", function () {
        document.getElementById("textopesquisa").value = "";
    });

    function Pesquisar() {
        var result = $('#textopesquisa').val();
        var idClinica = $('#idClinica').val();
        var url = "/Agendamento/ListaPartialView";
        var parametros = { pagina: 1, textopesquisa: result, idClinica: idClinica };
        $.get(url, parametros)
            .done(function (data) {
                $('#divpartial').html(data);
            });
    }

    function recarregarPagina() {
        location.reload();
    }

    document.getElementById("limpar").addEventListener("click", recarregarPagina);

    function VerificarDigitacao(e) {
        var code = (e.keyCode ? e.keyCode : e.which);
        if (code == 13) {
            Pesquisar();
        }
    }

    function Excluir(id) {
        var result = confirm("Tem certeza que quer excluir?");
        if (result) {
            var url = "/Agendamento/Excluir";
            var parametros = { id: id };
            $.get(url, parametros)
                .done(function (data) {

                    if (data.sucesso) {
                        document.location.reload(true);
                    } else {
                        alert(data.mensagem);
                    }

                });
        }
    }

</script>

Views/Agendamento/ListaPartialView.cshtml
@model X.PagedList.IPagedList<Agendamento>
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Código</th>
            <th>Paciente</th>

            <th>Especialidade</th>
            <th>Médico</th>

            <th>Data e Hora</em></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <td>@Model[i].Id</td>
                <td>@Model[i].NomePaciente</td>
                <td>@Model[i].NomeEspecialidade</td>
                <td>@Model[i].NomeMedico</td>
                <td>@Model[i].DataHora.ToString("dd/MM/yyyy HH:mm")</td>
                <td>
                    <input type="button" value="Editar" class="btn btn-dark"
                        onclick="javascript:window.location=`/Agendamento/Detalhe/${@Model[i].Id}`">
                    <input type="button" value="Excluir" class="btn btn-danger" onclick="Excluir(@Model[i].Id)">
                </td>
            </tr>
        }
    </tbody>
</table>
@Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina }))